DROP TABLE IF EXISTS USER_TABLE;
DROP TABLE IF EXISTS USER;
DROp TABLE IF EXISTS TOKEN_TABLE;
DROP TABLE IF EXISTS MOVIE_TABLE;
CREATE TABLE USER_TABLE
(
    ID       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME     TEXT                              NOT NULL,
    PASSWORD TEXT                              NOT NULL
);

INSERT INTO USER_TABLE (NAME, PASSWORD)
VALUES ('11712312', 'wowawesome');
select *
from USER_TABLE;


CREATE TABLE TOKEN_TABLE
(
    auto_ID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TOKEN_ID     TEXT                              NOT NULL,
    TOKEN_SECOND INT                               NOT NULL
);
INSERT INTO TOKEN_TABLE(TOKEN_ID, TOKEN_SECOND)
VALUES ('233333', 1603774016);
select *
from TOKEN_TABLE;

CREATE TABLE MOVIE_TABLE
(
    auto_ID    INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TITLE      TEXT UNIQUE                       NOT NULL,
    DATE_IN    TEXT                              NOT NULL,
    START_TIME TEXT                              NOT NULL,
    DURATION   TEXT                              NOT NULL,
    MOVIE_HALL TEXT                              NOT NULL,
    PRICE      TEXT                              NOT NULL,
    TYPE       TEXT                              NOT NULL
);
select *
from MOVIE_TABLE;
INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Dark Angels', '2020-10-11', '08:44', '115', '2', '114', 'Ordinary');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('White Scars', '2020-10-12', '08:45', '114', '3', '234', '3D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Space Wolves', '2020-10-13', '08:46', '113', '4', '123', '4D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Imperial Fists', '2020-10-14', '08:47', '112', '5', '435', '5D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Blood Angels', '2020-10-15', '08:48', '111', '6', '5623', '6D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Iron Hands', '2020-10-16', '08:49', '110', '7', '657', '7D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Ultramarines', '2020-10-20', '08:53', '106', '11', '6', '11D');
INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Salamanders', '2020-10-17', '08:50', '109', '8', '86', '8D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Raven Guard', '2020-10-18', '08:51', '108', '9', '90', '9D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Grey Knights', '2020-10-19', '08:52', '107', '10', '8', '10D');


INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Emperor''s Children', '2020-10-11', '08:44', '115', '2', '114', 'Ordinary');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Iron Warriors', '2020-10-12', '08:45', '114', '3', '234', '3D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Night Lords', '2020-10-13', '08:46', '113', '4', '123', '4D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('World Eaters', '2020-10-14', '08:47', '112', '5', '435', '5D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Death Guards', '2020-10-15', '08:48', '111', '6', '5623', '6D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Thousand Sons', '2020-10-16', '08:49', '110', '7', '657', '7D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Black Legion', '2020-10-20', '08:53', '106', '11', '6', '11D');
INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Word Bearers', '2020-10-17', '08:50', '109', '8', '86', '8D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Alpha Legion', '2020-10-18', '08:51', '108', '9', '90', '9D');

INSERT INTO MOVIE_TABLE (TITLE, DATE_IN, START_TIME, DURATION, MOVIE_HALL, PRICE, TYPE)
VALUES ('Red Corsairs', '2020-10-19', '08:52', '107', '10', '8', '10D');